# docker-compose.yaml
version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    #environment:
      #### WINDOWS ONLY ####
     # - DOCKER_HOST=tcp://host.docker.internal:2375
    privileged: true
    user: root
    ports:
      - 8083:8080
      - 50003:50000
    container_name: jenkins_tarea
    volumes:
      - ./jenkins_data:/var/jenkins_home
